language: java
jdk:
  - openjdk11
before_install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar
script:
  - ./gradlew clean
  - ./gradlew check
  - ./gradlew codeCoverageReport
  - ls -al
after_success:
  - bash <(curl -s https://codecov.io/bash) -f "./build/customJacocoReportDir/codeCoverageReport/codeCoverageReport.xml"